// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// This project keeps its secrets in .env.local (alongside the Clerk keys), which
// is what Next.js loads. dotenv defaults to .env, so point it at the same file.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
